import urllib.request
import zipfile
import io
import os
import re

def main():
    # 1. Download vscode-material-icon-theme repository zip
    print("Downloading vscode-material-icon-theme ZIP...")
    url = "https://github.com/PKief/vscode-material-icon-theme/archive/refs/heads/master.zip"
    req = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
    with urllib.request.urlopen(req) as response:
        zip_data = response.read()

    # 2. Extract SVGs to target directory
    target_dir = "/home/huy/Projects/zap/app/assets/bundled/svg/material"
    os.makedirs(target_dir, exist_ok=True)

    print("Extracting SVGs...")
    svg_count = 0
    with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
        for file_info in z.infolist():
            if "icons/" in file_info.filename and file_info.filename.endswith(".svg"):
                # The structure in zip is: vscode-material-icon-theme-master/icons/xxx.svg
                basename = os.path.basename(file_info.filename)
                if basename:
                    dest_path = os.path.join(target_dir, basename)
                    with open(dest_path, "wb") as f:
                        f.write(z.read(file_info))
                    svg_count += 1

    print(f"Extracted {svg_count} SVGs to {target_dir}")

    # 3. Read fileIcons.ts from zip
    print("Parsing fileIcons.ts...")
    ts_content = ""
    with zipfile.ZipFile(io.BytesIO(zip_data)) as z:
        for name in z.namelist():
            if name.endswith("src/core/icons/fileIcons.ts"):
                ts_content = z.read(name).decode("utf-8")
                break

    if not ts_content:
        print("fileIcons.ts not found in zip, downloading directly...")
        ts_url = "https://raw.githubusercontent.com/PKief/vscode-material-icon-theme/master/src/core/icons/fileIcons.ts"
        with urllib.request.urlopen(ts_url) as response:
            ts_content = response.read().decode("utf-8")

    # Let's parse ts_content using regex
    blocks = []
    # Match curly braces containing name: '...'
    for match in re.finditer(r'\{[^{}]*name:\s*\'([^\']+)\'[^{}]*\}', ts_content):
        block_str = match.group(0)
        name = match.group(1)
        
        # Extract fileExtensions
        ext_match = re.search(r'fileExtensions:\s*\[([^\]]*)\]', block_str)
        extensions = []
        if ext_match:
            exts_raw = ext_match.group(1)
            # Remove quotes, comments, spaces
            for part in exts_raw.split(","):
                part = re.sub(r'//.*', '', part) # strip comments
                part = part.strip(" '\"\r\n\t")
                if part:
                    extensions.append(part)
            
        # Extract fileNames
        name_match = re.search(r'fileNames:\s*\[([^\]]*)\]', block_str)
        filenames = []
        if name_match:
            names_raw = name_match.group(1)
            for part in names_raw.split(","):
                part = re.sub(r'//.*', '', part) # strip comments
                part = part.strip(" '\"\r\n\t")
                if part:
                    filenames.append(part)
            
        if extensions or filenames:
            blocks.append({
                'name': name,
                'extensions': extensions,
                'filenames': filenames
            })

    print(f"Parsed {len(blocks)} icon mappings.")

    # Generate Rust code
    rust_code = """// Generated by script/sync_material_icons.py. DO NOT EDIT.

pub fn get_file_icon(file_name: &str) -> Option<&'static str> {
    let lower_name = file_name.to_lowercase();
    
    // 1. Match exact file name (e.g. "dockerfile", "package.json")
    match lower_name.as_str() {
"""

    filename_map = {}
    for b in blocks:
        for fname in b['filenames']:
            filename_map[fname.lower()] = b['name']

    for fname, icon in sorted(filename_map.items()):
        escaped_fname = fname.replace('"', '\\"')
        rust_code += f'        "{escaped_fname}" => return Some("bundled/svg/material/{icon}.svg"),\n'

    rust_code += """        _ => {}
    }

    // 2. Match file extension (e.g. "rs", "ts")
    let parsed_path = std::path::Path::new(file_name);
    let extension = parsed_path.extension().and_then(|ext| ext.to_str())?.to_lowercase();
    match extension.as_str() {
"""

    ext_map = {}
    for b in blocks:
        for ext in b['extensions']:
            ext_map[ext.lower()] = b['name']

    for ext, icon in sorted(ext_map.items()):
        escaped_ext = ext.replace('"', '\\"')
        rust_code += f'        "{escaped_ext}" => Some("bundled/svg/material/{icon}.svg"),\n'

    rust_code += """        _ => None,
    }
}
"""

    rust_file = "/home/huy/Projects/zap/app/src/code/material_icons.rs"
    with open(rust_file, "w", encoding="utf-8") as f:
        f.write(rust_code)

    print(f"Generated {rust_file}")

if __name__ == "__main__":
    main()
